version: '3.9'

services:
 postgres:
   image: postgres:14-alpine
   ports:
     - 5432:5432
#    volumes:
#      - ~/apps/postgres:/var/lib/postgresql/data
   environment:
     - POSTGRES_PASSWORD=${PASSWORD}
     - POSTGRES_USER=${USER_NAME}
     - POSTGRES_DB=${DB_NAME}

 app:
   image: tools-rental-app-image:latest
   container_name: tools-rental-app
   depends_on:
     - postgres
   ports:
     - "8080:8080"
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
     SPRING_DATASOURCE_USERNAME: ${USER_NAME}
     SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
