#version: '3.9'
#
#services:
#  postgres:
#    image: postgres:14-alpine
#    ports:
#      - 5432:5432
##    volumes:
##      - ~/apps/postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=123
#      - POSTGRES_USER=user
#      - POSTGRES_DB=tools_rental_db
#
#  app:
#    image: tools-rental-app-image:latest
#    container_name: tools-rental-app
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tools_rental_db
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: 123
